version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - REACT_APP_TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REACT_APP_TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}