services:
  frontend:
    build:
      context: .
      target: production
    ports:
      - "3020:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      target: server
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}